### ISSUE TITLE
相关 ghproxy 代理即将下线

### ISSUE THREAD

**Issue by oneisall8955** [bestpvp/source#1]
我在去年还是前年的时候，接触了 tvbox 圈子，当时道长的 dr_py 项目在用的其他免费的 ghproxy 代理被消耗完了，想起我的 cf 搭建的只有我一个人在用，比较空闲，就贡献给道长的项目用了。

初期 dr_py 项目请求并没有多少，经过这段时间，这个代理地址在这个圈子有传播开的迹象，观察了下日志，发现请求你的这个项目请求比较频繁。

![image](https://github.com/user-attachments/assets/988a9bc8-85a0-4a50-b93c-2d449fd517d7)

![image](https://github.com/user-attachments/assets/602aeb22-0738-4644-b256-2bec417c5e2c)

很荣幸这个代理地址能参与到 tvbox圈子和你的项目。不过我还有其他项目也是基于 worker 在用，为了降低账号被 ban 的风险，并且担心到时候消耗完免费额度，影响其他项目，在此提前跟你说下，请理解。

![image](https://github.com/user-attachments/assets/197b0816-22f0-4109-85a8-27a0194e8404)

这个地址将在 2024 年 12 月15 号～31 号期间下线，麻烦到时请将你的相关项目修改成其他代理，或者用自己的账号搭建代理，谢谢～

**Comment by bestpvp** [comment]
感谢您的来信，我已知晓，谢谢你一路的支持，再次感谢

我会在本周进行切换，谢谢

码上插兜


> 2024年12月9日 23:27，刘志聪 ***@***.***> 写道：
> 
> 
> 我在去年还是前年的时候，接触了 tvbox 圈子，当时道长的 dr_py 项目在用的其他免费的 ghproxy 代理被消耗完了，想起我的 cf 搭建的只有我一个人在用，比较空闲，就贡献给道长的项目用了。
> 
> 初期 dr_py 项目请求并没有多少，经过这段时间，这个代理地址在这个圈子有传播开的迹象，观察了下日志，发现请求你的这个项目请求比较频繁。
> 
> 
> 
https://github.com/user-attachments/assets/602aeb22-0738-4644-b256-2bec417c5e2c
https://github.com/user-attachments/assets/988a9bc8-85a0-4a50-b93c-2d449fd517d7￼
988a9bc8-85a0-4a50-b93c-2d449fd517d7
PNG图像 · 296 KB
> 
>  <https://github.com/user-attachments/assets/602aeb22-0738-4644-b256-2bec417c5e2c>
> 很荣幸这个代理地址能参与到 tvbox圈子和你的项目。不过我还有其他项目也是基于 worker 在用，为了降低账号被 ban 的风险，并且担心到时候消耗完免费额度，影响其他项目，在此提前跟你说下，请理解。
> 
> 这个地址将在 2024 年 12 月15 号～31 号期间下线，麻烦到时请将你的相关项目修改成其他代理，或者用自己的账号搭建代理，谢谢～
> 
https://github.com/user-attachments/assets/197b0816-22f0-4109-85a8-27a0194e8404￼
197b0816-22f0-4109-85a8-27a0194e8404
PNG图像 · 41 KB

**Comment by oneisall8955** [comment]
> 感谢您的来信，我已知晓，谢谢你一路的支持，再次感谢 我会在本周进行切换，谢谢 码上插兜

🫰祝红红火火，一路长虹🚀🚀🚀
